<?php

$mapping = array(
    'Mautic\Api\Api' => __DIR__ . '/Mautic/Api/Api.php',
    'Mautic\Api\Assets' => __DIR__ . '/Mautic/Api/Assets.php',
    'Mautic\Api\CampaignEvents' => __DIR__ . '/Mautic/Api/CampaignEvents.php',
    'Mautic\Api\Campaigns' => __DIR__ . '/Mautic/Api/Campaigns.php',
    'Mautic\Api\Categories' => __DIR__ . '/Mautic/Api/Categories.php',
    'Mautic\Api\Companies' => __DIR__ . '/Mautic/Api/Companies.php',
    'Mautic\Api\CompanyFields' => __DIR__ . '/Mautic/Api/CompanyFields.php',
    'Mautic\Api\ContactFields' => __DIR__ . '/Mautic/Api/ContactFields.php',
    'Mautic\Api\Contacts' => __DIR__ . '/Mautic/Api/Contacts.php',
    'Mautic\Api\Data' => __DIR__ . '/Mautic/Api/Data.php',
    'Mautic\Api\Devices' => __DIR__ . '/Mautic/Api/Devices.php',
    'Mautic\Api\DynamicContents' => __DIR__ . '/Mautic/Api/DynamicContents.php',
    'Mautic\Api\Emails' => __DIR__ . '/Mautic/Api/Emails.php',
    'Mautic\Api\Files' => __DIR__ . '/Mautic/Api/Files.php',
    'Mautic\Api\Forms' => __DIR__ . '/Mautic/Api/Forms.php',
    'Mautic\Api\Leads' => __DIR__ . '/Mautic/Api/Leads.php',
    'Mautic\Api\Lists' => __DIR__ . '/Mautic/Api/Lists.php',
    'Mautic\Api\Messages' => __DIR__ . '/Mautic/Api/Messages.php',
    'Mautic\Api\Notes' => __DIR__ . '/Mautic/Api/Notes.php',
    'Mautic\Api\Notifications' => __DIR__ . '/Mautic/Api/Notifications.php',
    'Mautic\Api\Pages' => __DIR__ . '/Mautic/Api/Pages.php',
    'Mautic\Api\Points' => __DIR__ . '/Mautic/Api/Points.php',
    'Mautic\Api\PointTriggers' => __DIR__ . '/Mautic/Api/PointTriggers.php',
    'Mautic\Api\Reports' => __DIR__ . '/Mautic/Api/Reports.php',
    'Mautic\Api\Roles' => __DIR__ . '/Mautic/Api/Roles.php',
    'Mautic\Api\Segments' => __DIR__ . '/Mautic/Api/Segments.php',
    'Mautic\Api\Smses' => __DIR__ . '/Mautic/Api/Smses.php',
    'Mautic\Api\Stages' => __DIR__ . '/Mautic/Api/Stages.php',
    'Mautic\Api\Stats' => __DIR__ . '/Mautic/Api/Stats.php',
    'Mautic\Api\Themes' => __DIR__ . '/Mautic/Api/Themes.php',
    'Mautic\Api\Tweets' => __DIR__ . '/Mautic/Api/Tweets.php',
    'Mautic\Api\Users' => __DIR__ . '/Mautic/Api/Users.php',
    'Mautic\Auth\AbstractAuth' => __DIR__ . '/Mautic/Auth/AbstractAuth.php',
    'Mautic\Auth\ApiAuth' => __DIR__ . '/Mautic/Auth/ApiAuth.php',
    'Mautic\Auth\AuthInterface' => __DIR__ . '/Mautic/Auth/AuthInterface.php',
    'Mautic\Auth\BasicAuth' => __DIR__ . '/Mautic/Auth/BasicAuth.php',
    'Mautic\Auth\OAuth' => __DIR__ . '/Mautic/Auth/OAuth.php',
    'Mautic\Exception\AbstractApiException' => __DIR__ . '/Mautic/Exception/AbstractApiException.php',
    'Mautic\Exception\ActionNotSupportedException' => __DIR__ . '/Mautic/Exception/ActionNotSupportedException.php',
    'Mautic\Exception\AuthorizationRequiredException' => __DIR__ . '/Mautic/Exception/AuthorizationRequiredException.php',
    'Mautic\Exception\ContextNotFoundException' => __DIR__ . '/Mautic/Exception/ContextNotFoundException.php',
    'Mautic\Exception\IncorrectParametersReturnedException' => __DIR__ . '/Mautic/Exception/IncorrectParametersReturnedException.php',
    'Mautic\Exception\RequiredParameterMissingException' => __DIR__ . '/Mautic/Exception/RequiredParameterMissingException.php',
    'Mautic\Exception\UnexpectedResponseFormatException' => __DIR__ . '/Mautic/Exception/UnexpectedResponseFormatException.php',
    'Mautic\MauticApi' => __DIR__ . '/Mautic/MauticApi.php',
    'Mautic\QueryBuilder\QueryBuilder' => __DIR__ . '/Mautic/QueryBuilder/QueryBuilder.php',
    'Mautic\QueryBuilder\WhereBuilder' => __DIR__ . '/Mautic/QueryBuilder/WhereBuilder.php',
    'Psr\Log\AbstractLogger' => __DIR__ . '/Psr/Log/AbstractLogger.php',
    'Psr\Log\InvalidArgumentException' => __DIR__ . '/Psr/Log/InvalidArgumentException.php',
    'Psr\Log\LoggerAwareInterface' => __DIR__ . '/Psr/Log/LoggerAwareInterface.php',
    'Psr\Log\LoggerAwareTrait' => __DIR__ . '/Psr/Log/LoggerAwareTrait.php',
    'Psr\Log\LoggerInterface' => __DIR__ . '/Psr/Log/LoggerInterface.php',
    'Psr\Log\LoggerTrait' => __DIR__ . '/Psr/Log/LoggerTrait.php',
    'Psr\Log\LogLevel' => __DIR__ . '/Psr/Log/LogLevel.php',
    'Psr\Log\NullLogger' => __DIR__ . '/Psr/Log/NullLogger.php',
    'Psr\Log\Test\LoggerInterfaceTest' => __DIR__ . '/Psr/Log/Test/LoggerInterfaceTest.php',
);

spl_autoload_register(function ($class) use ($mapping) {
    if (isset($mapping[$class])) {
        require $mapping[$class];
    }
}, true);
